# Generated by Django 5.0.6 on 2024-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moto', '0002_moto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
