# Generated by Django 5.0.6 on 2024-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_dob_user_account_moto_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_moto',
            field=models.IntegerField(null=True),
        ),
    ]
