# Generated by Django 5.0.6 on 2024-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_account_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
